trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: UseNode@1
  displayName: 'Ensure Node.js'
  inputs:
    version: '12.x'

- bash: |
    sudo apt install -y \
      lcov \
      valgrind \
      libgmp-dev \
      gawk \
      wget \
      git
  displayName: 'Setup necessary packages'

- bash: './task.sh memcheck --xmlOutput Complex'
  displayName: 'Check for memory leaks'

- bash: |
    curl -sL https://github.com/shyiko/jabba/raw/master/install.sh | bash && . ~/.jabba/jabba.sh
    jabba install openjdk@1.11.0
    jabba use openjdk@1.11.0
    git clone https://github.com/cryptid-org/parsegrind
    cd parsegrind
    chmod +x mvnw
    ./mvnw clean package exec:java -Dexec.mainClass=cryptid.parsegrind.Application -Dexec.args=" \
      --base-directory=../ \
      --source-glob=**/*.c \
      --valgrind-glob=**/*.memcheck.xml \
      --output=../memcheck.html"
    cd ..
  displayName: 'Run parsegrind'
  condition: succeededOrFailed()

- task: PublishBuildArtifacts@1
  displayName: 'Publish parsegrind HTML output'
  condition: succeededOrFailed()
  inputs:
    pathToPublish: 'memcheck.html'
    artifactName: 'memcheck-html'
